pw_louvre_home:
    path:      /
    defaults:
        _controller: PWLouvreBundle:Core:index

pw_louvre_reservation:
    path:      /reservation
    defaults:
        _controller: PWLouvreBundle:Core:reservation