services:
    pw_louvre.dateControl:
        class: PW\LouvreBundle\Services\PWDateControl
    pw_louvre.ageCalculation:
        class: PW\LouvreBundle\Services\PWAgeCalculation    
    pw_louvre.priceCalculation:
        class: PW\LouvreBundle\Services\PWPriceCalculation
        arguments: 
          - "@pw_louvre.ageCalculation"
    pw_louvre.checkoutValidation:
        class: PW\LouvreBundle\Services\PWCheckoutValidation
    pw_louvre.mailerService:
        class: PW\LouvreBundle\Services\PWMailerService
        arguments:
            - "@mailer"
            - "@templating"

